/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DaysCardView: typeof import('./src/components/DaysCardView.vue')['default']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    FileLoader: typeof import('./src/components/FileLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YaMap: typeof import('./src/components/YaMap.vue')['default']
  }
}
